server:
  port: ${SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://authservice
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://authservice
          predicates:
            - Path=/api/users/**

        - id: admin-service
          uri: lb://adminservice
          predicates:
            - Path=/api/admin/**

        - id: catalog-service
          uri: lb://catalogservice
          predicates:
            - Path=/api/catalog/**,/api/products/**,/api/categories/**

        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/api/cart/**,/api/checkout/**,/api/orders/**

        - id: payment-service
          uri: lb://paymentservice
          predicates:
            - Path=/api/payments/**,/api/payments/internal/**

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
